spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/zadb?currentSchema=za'
    username: 'postgres'
    password: 'postgrespass'
  flyway:
    baseline-on-migrate: true
    schemas: 'za'
